[env:seeed_xiao_esp32c6]
platform = espressif32
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    knolleary/PubSubClient @ ^2.8

build_flags =
    -D CORE_DEBUG_LEVEL=1
